### ISSUE TITLE
not find file in ages_to_buctets.py 

### ISSUE THREAD

**Issue by DuTim** [Anna146/PRIDE#2]
![image](https://user-images.githubusercontent.com/50939742/149489237-adcf1cb2-26b2-4cc4-b6f2-4b2771fd7498.png)
I don't find  like movie_name_chaging_dict.txt  file , Are you sure you uploaded it?

**Comment by Anna146** [comment]
Oops sorry my bad. I uploaded the file, pls find it in the /data/ folder and updated code of ages_to_buckets.py
Thanks!
